### ISSUE TITLE
CanGetABIComponent async

### ISSUE THREAD

**Issue by JFGHT** [ProphetDaniel/drizzle-react-components#3]
Theres a problem with `this.getContract().abi;`.

When you're coming from another page you (might) already have the contracts but if you refresh the page where the component is, you don't have the contracts at the beginning; the data will come later. So in this case theres no `abi` and it consecuently throws:

> Cannot read property 'abi' of undefined

**Comment by ProphetDaniel** [comment]
This problem looks to be inherited from [drizzle-react-components](https://github.com/trufflesuite/drizzle-react-components).


More information here: https://github.com/trufflesuite/drizzle-react-components/issues/34

**Comment by JFGHT** [comment]
It's of course working if you envelop the component with the LoadingContainer. Probably it's done like that on purpose?

**Comment by ProphetDaniel** [comment]
> It's of course working if you envelop the component with the LoadingContainer. Probably it's done like that on purpose?


Exactly @JFGHT . Loading Container is responsible to properly initialize the web3 instance.
